# Generated by Django 5.0.6 on 2024-08-18 10:28

import django.db.models.deletion
import phonenumber_field.modelfields
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('student_id', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=students.models.upload_location)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('parent_name', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('is_prefect', models.BooleanField(default=False)),
                ('is_repeater', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.schoolclass')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
